import './globals.css'
import { Inter } from 'next/font/google'
import ProviderState from './redux/ProviderState'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Horas de trabajo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ProviderState>
        <body className={inter.className}>{children}</body>
      </ProviderState>
    </html>
  )
}
